### ISSUE TITLE
Duplicate paragraphs pages 67-68

### ISSUE THREAD

**Issue by rafaelpac** [VladdyC/BTCTKVR-Magazine#1]
Hey Vlad! There is a little bug on pages 67-68: the last four paragraphs on page 67 are repeated on page 68.

**Comment by VladdyC** [comment]
Yeah, sorry for that. Will talk to my graphic designer, as the issue doesn't exist in the original article.

Thanks for submitting the PR!

**Comment by VladdyC** [comment]
Fixed it today. Now you can find a revised version of pages 66-67 and 68-69 with a bonus image that you won't find in any of the printed magazines. Thank you for reporting the issue!
